### ISSUE TITLE
Is it possible to use this software to find the Private Key in ECDSA?

### ISSUE THREAD

**Issue by amiwrcd** [pablocelayes/rsa-wiener-attack#4]
Hello! Is it possible to use this software to find the Private Key in ECDSA? I have a list of over 10,000,000 compressed Bitcoin public keys. I would like to apply this to my project. It is necessary to find one or two Private Keys from the entire list of public keys.

**Comment by pablocelayes** [comment]
Hi @amiwrcd , thanks for your interest in my project.
I am not familiar with the ECDSA scheme, but if you think this can help, please go ahead and use it.
Let me know how it worked for you, I am curious about the results.

**Comment by Gurenduben** [comment]
Did it work?
